apiVersion: v2
appVersion: “1.0”
description: A Helm chart to configure resources for cert-manager to work with
name: cert-manager
version: 0.1.0
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.6.1
    
